### ISSUE TITLE
[Action Required] Migrate your OAuth out-of-band flow to an alternative method before Oct. 3, 2022

### ISSUE THREAD

**Issue by spkane** [google/calblink#25]
It appears that the OAuth approach used by this tool is being deprecated. Is this correct, or is there an easy way to migrate this to the newer OAuth system?

---

**[Action Required] Migrate your OAuth out-of-band flow to an alternative method before Oct. 3, 2022**

- Google Developers <GoogleDevelopers-noreply@google.com>
- May 3, 2022, 8:26 PM

Our records indicate you have OAuth clients that used the OAuth OOB flow in the past.

---

Hello Google OAuth Developer,

We are writing to inform you that OAuth out-of-band (OOB) flow will be deprecated on October 3, 2022, to protect users from phishing and app impersonation attacks.

**What do I need to know?**
Starting October 3, 2022, we will block OOB requests to Google’s OAuth 2.0 authorization endpoint for existing clients. Apps using OOB in testing mode will not be affected. However, we strongly recommend you to migrate them to safer methods as these apps will be immediately blocked when switching to in production status.

**Note**: New OOB usage has already been disallowed since February 28, 2022.

Below are key dates for compliance

**September 5, 2022**: A user-facing warning message may be displayed to non-compliant OAuth requests
**October 3, 2022**: The OOB flow is blocked for all clients and users will see the error page.
Please check out our recent blog post about Making Google OAuth interactions safer for more information.

**What do I need to do?**
Migrate your app(s) to an appropriate alternative method by following these instructions:

- Determine your app(s) client type from your Google Cloud project by following the client links below.
- Migrate your app(s) to a more secure alternative method by following the instructions in the blog post above for your client type.
- If necessary, you may request a one-time extension for migrating your app until January 31, 2023. Keep in mind that all OOB authorization requests will be blocked on February 1, 2023.

The following OAuth client(s) will be blocked on Oct 3, 2022.

OAuth client list:

- **Project ID**: _REDACTED_
- **Client**: _REDACTED_

Thanks for choosing Google OAuth.

— The Google OAuth Developer Team

© 2022 Google LLC 1600 Amphitheatre Parkway, Mountain View, CA 94043

You have received this mandatory service announcement to update you about important changes to Google services you use.

**Comment by spkane** [comment]
@kazrakcom Do you know if I just need to change something on my side, or if this will require code changes in `calblink` to support?

**Comment by spkane** [comment]
Thanks! I honestly love this tool and would hate to lose access to it. That little LED does a good job of pulling me out of a coding trance and making sure I show up to appointments and meetings on time. :-)

**Comment by kazrakcom** [comment]
Okay, yes, this will require some code updates.  (I just got the same email.)  I don't think they'll be that bad, and hopefully I'll have an update out by the end of next week.

**Comment by kazrakcom** [comment]
I don't see an easy fix for this in the golang OAuth2 code at the moment, so I'm going to push on them a bit for a general solution instead of rolling my own.  If it looks like they aren't going to sort it out quickly enough, then I'll roll my own and maybe see if I can push something upstream.  But I doubt that will be necessary.

**Comment by kazrakcom** [comment]
Update on this: as there has been no movement on the Calendar API doc front, I've worked up a fix to this myself.  I'm going to run it past some friends of mine that are better at Go to confirm it isn't completely horrible before I release it, but it should be out soon.
