### ISSUE TITLE
Feature request: Support multiple calendars

### ISSUE THREAD

**Issue by spkane** [google/calblink#9]
Support multiple calendars.

e.g. If I share a home calendar with my work account, it would be super helpful to be able to get alerts for events on both calendars, if desired.

**Comment by kazrakcom** [comment]
I'll see what I can do on this - would you want them to both trigger events indistinguishably, or to have (for example) one side of a blink(1) for one calendar and the other side for the other calendar?

**Comment by spkane** [comment]
I'd be fine with it simply letting me know that I have something coming up on ANY of the calendars that are passed in via an array/list, since I would typically have a web tab open that has the ones I care about in a shared view.

I did a horrible hack to get this working in my fork, but it is clumsy at best (and likely has a few bugs)

**Comment by kazrakcom** [comment]
I'll look into this tomorrow, although it may take some time before I can merge it into this repo.  (I hadn't updated recently enough and lost commit access to Google repos, and the people who can restore it are out for the holidays.)  It could be a very handy feature for me as well.

**Comment by kazrakcom** [comment]
My pull request is at https://github.com/google/calblink/pull/17 for this.  Hopefully after the New Year I can get these pull requests merged in.

**Comment by spkane** [comment]
@kazrakcom Were you able to get your commit access back? I'd be happy to do some testing as well, if it would help.

**Comment by kazrakcom** [comment]
I have commit access again, and have merged in my pull requests.  If you run into issues, please reopen this and/or open a new issue.
